from typing import Union, Optional

# Standard encoding
def b64encode(s: Union[bytes, bytearray], altchars: Optional[bytes] = None) -> bytes: ...
def b64decode(s: Union[bytes, bytearray, str], altchars: Optional[bytes] = None, validate: bool = False) -> bytes: ...
def standard_b64encode(s: Union[bytes, bytearray]) -> bytes: ...
def standard_b64decode(s: Union[bytes, bytearray, str]) -> bytes: ...

# URL-safe encoding
def urlsafe_b64encode(s: Union[bytes, bytearray]) -> bytes: ...
def urlsafe_b64decode(s: Union[bytes, bytearray, str]) -> bytes: ...